spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product_category_service
    username: root
    password: rootroot


  liquibase:
    change-log: classpath:/db/changelog/migration.xml

jwt:
  secret: kscfadcad@29
  expiration: 330000


